---
title: "CBC cleaning"
author: "Francis Joyce"
date: "2020-12-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(janitor)
library(readr)
library(naniar)
library(lubridate)
library(stringr)
library(purrr)
library(tidyr)
library(knitr)
library(kableExtra)
library(here)
```

Download data from here: https://netapp.audubon.org/cbcobservation/historical/resultsbycount.aspx#

Use count code CRCA

Start year = 111 (2010)
End year = 120 (2019)

CSV, sort Taxonomic

Then, delete non-species count top rows.

ALso delete the rows below for participants...

Rename so that the columns are:

species
count_year
how_many_cw	
number_by_party_hours
flags




```{r}
CRCA_cbc <- read_csv(here("data/CRCA-2010-2019_pre-cleaned.csv"))
```


```{r}
CRCA_cbc %>%
  head() %>%
  kable() %>%
  kable_styling(full_width = FALSE, position = "left")

```


```{r}
CRCA_cbc %>% 
  filter(row_number() == 1) %>% 
  pull(species)
```

```{r}
# Putting it together: Mutating the two variables
CRCA_cbc <- CRCA_cbc %>%
  mutate(species_latin = str_extract(species, "(?<=\\[).+?(?=\\])"),
         species = word(species, start = 1, sep = fixed('\n[')))
```


```{r}
CRCA_cbc %>% 
  filter(row_number() == 15133) %>% 
  pull(count_year)
```

```{r}
count_participant_meta_data <- CRCA_cbc %>%
  distinct(participant_info = count_year) %>%
  mutate(year = word(participant_info)) %>%
  mutate(number_of_participants = str_extract(
    participant_info, "(?<=Participants:\\s).+?(?=\\s#)")) %>%  # Gets everything between "Participants: " and " #"
  mutate(species_reported = str_extract(
    participant_info, "(?<=Reported:\\s).+?(?=\\nTotal)")) %>%  # Gets everything between "Reported: " and "Total"
  mutate(total_hours = str_extract(
    participant_info, "(?<=Hrs\\.:\\s).*$"))  # Gets everything after "Hrs.: "
# This regex is different because it goes until the end of the string:
# https://forum.sublimetext.com/t/regex-match-everything-after-this-word/20764

count_participant_meta_data %>%
  head(n = 3) %>%
  kable() %>%
  kable_styling(full_width = FALSE, position = "left")
```


```{r}
CRCA_cbc <- CRCA_cbc %>%
  rename(participant_info = count_year,
         how_many_counted = how_many_cw) %>%
  mutate(year = as.integer(word(participant_info)),  # We will keep year and total_hours
         total_hours = as.double(
           str_extract(
             participant_info, "(?<=Hrs\\.:\\s).*$")))
```

```{r}
CRCA_cbc <- CRCA_cbc %>%
  select(year, species, species_latin, how_many_counted, total_hours)
```


```{r}
#remove cw records
CRCA_cbc <- CRCA_cbc %>%
  mutate(how_many_counted = ifelse(how_many_counted == "cw", NA, how_many_counted),
         how_many_counted = as.integer(how_many_counted))
```

```{r}
#filter out generic IDs?
CRCA_cbc %>%
filter(str_detect(species, "sp\\.")) %>%
distinct(species)
```


```{r}
CRCA_cbc <- CRCA_cbc %>%
  filter(!(str_detect(species, "sp\\.")))
```

```{r}
CRCA_cbc <- CRCA_cbc %>%
  mutate(how_many_counted = replace_na(how_many_counted, 0),
         how_many_counted_by_hour = as.double(how_many_counted) / total_hours)
```

```{r}
CRCA_cbc %>%
  head() %>%
  kable() %>%
  kable_styling(full_width = FALSE, position = "left")
```

Move this file manually to the root directory

```{r}
write_csv(CRCA_cbc, "CRCA-CBC-2019-cleaned.csv")
```

